### ISSUE TITLE
Please simplify readme for average joe.

### ISSUE THREAD

**Issue by omrzgit** [minanagehsalalma/Youtube-Downloader-Bookmarklet#1]
Readme defines How It works well
but does not define well enough  How to Use..
Should be simplified.

**Comment by minanagehsalalma** [comment]
> Readme defines How It works well but does not define well enough How to Use.. Should be simplified.

hello master average joe, i am uploading a video now.

**Comment by minanagehsalalma** [comment]
@T21yx64 check it now.

**Comment by omrzgit** [comment]
thank-you so much, its a great script! keep up the great work! <3
